/**
 * The Farm-Fresh icons members can pick (src/components/ui/farmIcons.ts has
 * them all): for a forum section, a forum topic and a post on a Kudde's
 * Prikbord. In groups, for the picker (src/components/ui/IconPicker.tsx).
 */
export const ICON_GROUPS = {
  'Praten': ['comment', 'comments', 'comment_white', 'new_comment', 'comment_box', 'show_comment', 'user_comment', 'email', 'email_at_sign', 'help', 'question', 'information', 'exclamation', 'warning', 'lightbulb', 'flag_red', 'flag_new', 'flag_hot', 'tag_blue', 'tag_green', 'tag_pink', 'tag_purple', 'tag_orange', 'tag_yellow', 'tags_cloud', 'bookmark', 'note', 'note_pin', 'newspaper', 'document_comments', 'group', 'user', 'kids', 'baby_bottle', 'heart', 'heart_half', 'heart_break', 'star', 'emotion_happy'],
  "Hobby's": ['book', 'books', 'books_stack', 'bookshelf', 'book_open', 'e_book_reader_black', 'pencil', 'pencil_ruler', 'paintbrush', 'brushes', 'paint_tube', 'paintcan', 'palette', 'color_swatch', 'color_wheel', 'draw_star', 'camera', 'camera_black', 'camera_lens', 'photo', 'photo_album', 'picture_frame', 'picture_sunset', 'theater', 'mask', 'chefs_hat', 'party_hat', 'card_gift', 'teddy_bear', 'wizard', 'wizard_women', 'hat', 'shirt_polo', 'shoe', 'education', 'wand', 'key', 'rosette', 'rosette_2'],
  'Muziek en film': ['music', 'acoustic_guitar', 'electric_guitar', 'piano', 'drum', 'microphone', 'headphone', 'headphone_mic', 'ipod', 'radio_modern', 'radio_oldschool', 'cd', 'cd_case', 'sound', 'film', 'film_photo', 'camcorder', 'cinema_ticket', 'ticket_stub', 'popcorn', 'television', 'lcd_tv', 'video', 'youtube', 'satellite_dish', 'transmit'],
  'Spellen en sport': ['controller', 'joystick', 'game_monitor', 'board_game', 'playing_cards', 'dice', 'chess_horse', 'chess_king', 'chess_queen', 'checkerboard', 'sport_soccer', 'sport_basketball', 'sport_football', 'sport_golf', 'sport_tennis', 'sport_raquet', 'sport_shuttlecock', 'sport_8ball', 'sport', 'cup', 'cup_gold', 'cup_silver', 'cup_bronze', 'medal_gold_1', 'medal_award_gold', 'award_star_gold_1', 'crown_gold', 'crown_silver', 'crown_bronze', 'flag_finish'],
  'Eten en drinken': ['cutlery', 'cup', 'drink', 'beer', 'wine_pairings', 'cake', 'piece_of_cake', 'cookies', 'cookie_chocolate', 'gingerbread_man', 'candy_cane', 'donut', 'icecream', 'ice_cube', 'pizza', 'hamburger', 'soup', 'bread', 'cheese', 'sushi', 'steak_fish', 'apple', 'fruit_grape', 'fruit_lime'],
  'Natuur en weer': ['flower', 'butterfly', 'cactus', 'leaf_plant', 'plant', 'tree', 'tree_red', 'tree_yellow', 'acorn', 'cat', 'dog', 'rabbit', 'snail', 'clown_fish', 'spider_web', 'sun_cloudy', 'weather_sun', 'weather_clouds', 'weather_rain', 'weather_snow', 'weather_lightning', 'rainbow', 'rainbow_cloud', 'sun_rain', 'snow_rain', 'moon', 'half_moon', 'weather_moon_cloudy', 'umbrella', 'fire', 'lightning', 'snowman', 'christmas_tree'],
  'Reizen en plekken': ['world', 'globe_africa', 'globe_australia', 'globe_model', 'map', 'compass', 'location_pin', 'house', 'house_one', 'house_two', 'building', 'church', 'hospital', 'bank', 'shop', 'car', 'car_taxi', 'bus', 'train', 'train_metro', 'plane', 'paper_airplane', 'cruise_ship', 'rocket', 'anchor', 'luggage_brown_tag', 'basket_shopping', 'shopping', 'cart', 'money_bag', 'coins', 'coins_in_hand', 'wallet'],
  'Techniek': ['computer', 'laptop', 'monitor', 'mouse', 'keyboard', 'iphone', 'phone_vintage', 'phone_handset', 'telephone', 'printer', 'code', 'page_white_code', 'bug', 'tux', 'cog', 'wrench_orange', 'hammer', 'magnet', 'microscope', 'flask', 'satellite', 'lightbulb_off', 'battery_full', 'plugin', 'lock', 'shield', 'cctv_camera'],
  'Bijzonder': ['diamond', 'ruby', 'faberge_egg', 'skull_old', 'trojan_horse', 'bomb', 'radioactivity_drum', 'hourglass', 'clock', 'calendar', 'bell', 'award_star_gold_3', 'brain', 'emotion_pumpkin', 'rainbow', 'walk', 'umbrella_folded'],
} as const satisfies Record<string, readonly string[]>

export const PICKABLE_ICONS = [...new Set(Object.values(ICON_GROUPS).flat())] as [string, ...string[]]
export const isPickableIcon = (v: unknown): v is string => typeof v === 'string' && (PICKABLE_ICONS as string[]).includes(v)
