import type { GadgetType } from '../../../shared/gadgets'
import type { FarmIconName } from '../../components/ui/farmIcons'

export const GADGET_ICONS: Record<GadgetType, FarmIconName> = {
  notities: 'note',
  muziek: 'music',
  video: 'film',
  aftellen: 'hourglass',
  poll: 'chart_bar',
  kuddesvideo: 'television',
  prestaties: 'award_star_gold_1',
  boeken: 'book',
  films: 'film',
  platen: 'sound',
  spellen: 'joystick',
  recepten: 'cutlery',
  kanaal: 'camcorder',
  radio: 'transmit',
  klok: 'clock',
  lijstje: 'text_list_numbers',
  landen: 'world',
  links: 'world_link',
  mariokart: 'flag_finish',
  tekst: 'page_white_edit',
  foto: 'photo',
  teller: 'chart_bar',
  citaat: 'comment',
  drank: 'drink',
  series: 'television',
  huisdier: 'cat',
  forum: 'comments',
  plakboek: 'book_picture',
  spelscores: 'medal_gold_1',
  blog: 'book_open',
  fotografie: 'camera',
  kuddesmuziek: 'cd',
  kuddesradio: 'transmit',
  mindfulness: 'flower',
  bestanden: 'folder_page',
  woord: 'page_white_word',
  rekenblad: 'page_white_excel',
  presentatie: 'page_white_powerpoint',
  paint: 'paintbrush',
  mindmap: 'chart_organisation',
  planner: 'calendar_view_week',
  formulier: 'application_form',
  kladblok: 'note',
  rekenmachine: 'calculator',
}
